# Generated by Django 6.1 on 2026-08-13 10:40

import django.core.validators
import reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_comments_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(reviews.models.current_year, message='Год выпуска не может быть больше текущего!')], verbose_name='Год выпуска'),
        ),
    ]
